### PR TITLE
Added fiat currency list supported by cryptocompare

### PR DESCRIPTION
**Pull request by abhishekgahlot**

### CODE REVIEW

**Comment by abhishekgahlot** [comment]
This fixes the issue: https://github.com/ExodusMovement/cryptocompare/issues/24

**Comment by abhishekgahlot** [comment]
It was tested using following code snippet and found out which currencies are supported by cryptocompare: 
```

const cryptocompare = require('cryptocompare');
global.fetch = require('node-fetch')

const globalCurrencies = ["USD","CAD","EUR","AED","AFN","ALL","AMD","ARS","AUD","AZN","BAM","BDT","BGN","BHD","BIF","BND","BOB","BRL","BWP","BYR","BZD","CDF","CHF","CLP","CNY","COP","CRC","CVE","CZK","DJF","DKK","DOP","DZD","EEK","EGP","ERN","ETB","GBP","GEL","GHS","GNF","GTQ","HKD","HNL","HRK","HUF","IDR","ILS","INR","IQD","IRR","ISK","JMD","JOD","JPY","KES","KHR","KMF","KRW","KWD","KZT","LBP","LKR","LTL","LVL","LYD","MAD","MDL","MGA","MKD","MMK","MOP","MUR","MXN","MYR","MZN","NAD","NGN","NIO","NOK","NPR","NZD","OMR","PAB","PEN","PHP","PKR","PLN","PYG","QAR","RON","RSD","RUB","RWF","SAR","SDG","SEK","SGD","SOS","SYP","THB","TND","TOP","TRY","TTD","TWD","TZS","UAH","UGX","UYU","UZS","VEF","VND","XAF","XOF","YER","ZAR","ZMK"];
const supportedCurrencies = [];

const timer = setInterval(function () {
    let globalCurrency = y.pop();
	if (! globalCurrency) { clearInterval(timer); return; }
	cryptocompare.convert('BTC', globalCurrency).then((data) => {
        console.log(data)
        supportedCurrencies.push(data);
    });
}, 100);
```

**Comment by kennedybaird** [comment]
Thanks for this, I was going to do it but I read somewhere that the maintainers don't want to handle their own lists in the package, rather it just functioning as an api.

**Comment by RyanZim** [comment]
Closing as per @kennedybaird.

**Pull request closed without merging**
