### PR TITLE
Adding coinList function to complete API (more tests required)

### PR DESCRIPTION
**Pull request by kwiksand**
I needed coinList for a project I was working on in addition to the other methods, already available.  Seemed simple to add it here

### CODE REVIEW

**Comment by RyanZim** [comment]
This module only exposes https://min-api.cryptocompare.com/data/

@jprichardson Should we add methods that use the old API? I'm personally not in favor of it.

**Comment by jprichardson** [comment]
@RyanZim I think we can, at this point not a huge priority. 

@vcealicu - is the old API (non-min) going to be deprecated, or do you plan on keeping it around?

**Comment by kwiksand** [comment]
Hi @jprichardson / @RyanZim: I hadn't realised the other API url was actually deprecated, don't want you to be using old/unnecessary functionality.  Definitely not a priority at all, just thought someone else may need/use it as well.

Close this, by all means!

**Comment by PhearZero** [comment]
Endpoint is now available at data/all/coinlist #10

**Comment by RyanZim** [comment]
#10 implemented the same thing using `min-api`; released in 0.3.0; closing.

**Pull request closed without merging**
