### PR TITLE
Add exchange option for histoXXX()

### PR DESCRIPTION
**Pull request by fasheng**
Besides, thanks for the great job!

### CODE REVIEW

**Comment by jprichardson** [comment]
@RyanZim will you publish a new minor?

**Comment by RyanZim** [comment]
Sure

**Comment by RyanZim** [comment]
Release is pushed to git, @jprichardson I don't have npm access to publish it.

**Comment by jprichardson** [comment]
@RyanZim added.

**Comment by RyanZim** [comment]
Published

**Pull request merged**
